### ISSUE TITLE
🏁 Persistent games 

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#101]
# goal

You should be able to completely close out your browser during a game, then revisit the website and get caught up on the same game. Use the persistent client ID and the history provider to do this

## prerequisites 

- [x] We need a highly visible QUIT button. Complete #129 before starting this ticket.
- [x] We need players to be able to pass. Complete #56. Include the PASS button as part of #129.  
- [x] The pass button should trigger a dialog on the opponent's side, so that the opponent is aware that the other player passed (#157).
- [x] Completed #59. We now provide long lasting client ID in browser 

## quit command 

- [x] complete #153 

## check for participation in a game

- [ ] After player receives ID ACK from gateway, we must **determine whether they belong in a game**. If so, send along board size, client's color, turn, playerUp, and moves (#282) 
- [ ] Add gateway request/reply management (#283)
- [ ] browser needs to play out the game turn by turn based on `ParticipationReply`

## tracking end of game 

Completed in #163: 

- [x] explicitly manage data tracking whether a user has QUIT a game, or whether both players have PASSED

```kotlin
enum class Participation {
  InProgress, // game ready event from lobby
  Finished, // at least one player quit, or both players passed consecutively
}
```

**Comment by Terkwood** [comment]
Related: #109

It would be wise to implement the disconnect warning prior to adding an entirely new management layer for resuming games

**Comment by Terkwood** [comment]
Create Game stream holds the creator client ID.

**Comment by Terkwood** [comment]
We may need to add client ID back into the game lobby flow so that it can propagate down to the Participation layer.

**Comment by Terkwood** [comment]
![IMG_20200105_090717-01](https://user-images.githubusercontent.com/38859656/71781299-eca61d80-2f9a-11ea-9ce6-6f952b5d8d8b.jpeg)

Either this, or alter GameReady to hold client IDs

**Comment by Terkwood** [comment]
This ticket needs to be completely reworked to account for micro stack considerations. See #325
