### ISSUE TITLE
Player report: lock-up when switching from Wifi to Cellular

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#110]
# Report 

> Apparently it locked up for her and went to WhatsApp, where I had sent her the link
> It may have just been a case of her WiFi signal going in and out. When it came back she moved and I couldn't see where.
> The problem is that she has her own internet connection as well...
> So when WiFi goes out she has the other
> Seems to be the switch from one to the other that caused the problem

One should be able to reproduce this by cutting wifi connection and letting cellular take over.

## Tasks

- [x] improve detection of network d/c
- [x] show dialog during d/c
- [x] extra aggressive checking
- [x]  request history on reconnect if GENMOVE (see #111)
- [x] prevent "Negotiating Game Venue" and other dialogs from overlapping with Reconn Dialog

**Comment by Terkwood** [comment]
Solving #101 would work around this, even without having the root cause figured out

**Comment by Terkwood** [comment]
Does player use iPhone or Android? On Android, linking via whatsapp just moves you over to the browser completely. I wonder if they hit the BACK button?

**Comment by Terkwood** [comment]
Related: #109

It would be wise to show the disconnect warning prior to embarking on a quixotic bugfix path
