### ISSUE TITLE
❣️SYNC: Recover from deadlock

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#136]
Allow clients to sync up with the service layer and remedy:

- lost move with [both people waiting for each other](https://github.com/Terkwood/BUGOUT/issues/136#issuecomment-621507983) ⚰️ 
- incorrect turn
- missed the other player's move

These data should be regularly tranmitted via a client-initiated REQSYNC event.  

Compare broadcasted board positions and if they don't match, wipe client board clean and replace it with  data from the `SyncReply` event

## services must accept missed client moves 

As part of the REQSYNC payload, services must accept a client move that was missed. Compare client view of turn number, player_up to server view. Output MakeMove if server needs to catch up to a missed move 

## data flow 

Make a request to history using key = game_id. Re-use the req_id provided from the client. Carefully match the reply req_id.  Calculate the turn and player_up based on the history provider reply.

## known issues

gateway `PLAYERUP` can be inaccurate (#150), so don't rely on that.  Create a new subsystem which handles this.

### Requesting sync from browser

```json
{ 
  "type": "ReqSync",
  "reqId": "0489f9d3-ca12-476d-99b9-6f062060adbb",
  "playerUp": "BLACK",
  "turn": 1,
  "lastMove":  null
}

{ 
  "type": "ReqSync",
  "reqId": "ac467085-abbc-4fda-adc8-9b41161333e7",
  "playerUp": "WHITE",
  "turn": 2,
  "lastMove":  {"turn": 1, "player": "BLACK", "coord": { "x": 4, "y": 4 } }
}
```

### Sync reply sent from server

```json
{
  "type": "SyncReply",
  "replyTo": "ac467085-abbc-4fda-adc8-9b41161333e7",
  "playerUp": "WHITE",
  "turn": 2,
  "moves": [
    { "turn": 1, "player": "BLACK", "coord": { "x": 4, "y": 4 } } 
  ] 
}
```

Consider that the reply should be routed by session ID, not game ID. This will avoid spamming the other player. So the backend req/reply needs to use that field. 

## browser work

Use [SabakiHQ immutable game tree](https://github.com/SabakiHQ/immutable-gametree/blob/v1.7.2/src/GameTree.js) and its [Draft.removeNode method](https://github.com/SabakiHQ/immutable-gametree/blob/439edd0d0c8b8c4df1d6e7fb40948067463c1e82/src/Draft.js#L105)

### sabaki gamestate

Look at the following data structure:

```js
let {gameTrees, gameIndex} = sabaki.state
let {currentPlayer} = sabaki.inferredState
```

![gametrees](https://user-images.githubusercontent.com/38859656/80657838-b5301500-8a52-11ea-8995-842811dc9658.png)

## Timing 

Browser must track the reqId for the last REQSYNC sent. If a SYNCREPLY doesn't matched that reqId, discard it. 

If browser sends MAKEMOVE, it must discard the last REQSYNC ID and delay the next REQSYNC.

If browser receives MOVEMADE, it should discard the last REQSYNC ID and delay the next REQSYNC.

## Do not hash moves 

Don't worry about the size of payloads at this point, just get the strategy right 

## Sort of related

See #135, #118

## Tasks

- [x] complete browser work
- [x] draft gateway changes
- [x] draft sync service 
- [x] perform hack testing in dev
- [x] white should be able to miss the very first turn
- [x] sync: respond with system view in edge cases

**Comment by Terkwood** [comment]
gateway `PLAYERUP` is just wrong sometimes...

**Comment by Terkwood** [comment]
https://github.com/digitalbazaar/forge/blob/master/README.md#sha256

**Comment by Terkwood** [comment]
With the resolution of #137, hung games are now pretty rare.

**Comment by Terkwood** [comment]
After a long period of satisfactory behavior, we did witness a hung game which this effort would most likely solve. Both clients were continually connected to gateway and the Make Move event was correctly intercepted, but was either not processed, or the response was not delivered.

**Comment by Terkwood** [comment]
This can be difficult to detect if you watch server logs.  We saw it happen today in a multiplayer game, and there were no errors in any service, and the client _may have been connected continuously_.  Client sent a move but it was never received by server.

If we had periodic game state announcement we could account for this.

**Comment by Terkwood** [comment]
![IMG_20200430_051949-01](https://user-images.githubusercontent.com/38859656/80694318-585c4b00-8aa2-11ea-9c4e-203eb04a2bbd.jpeg)
