### ISSUE TITLE
Implement micro-changelog

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#175]
## TODO: test

- [ ] minimal integration test 

## TODO: impl

- [x] dedupe common model data and update micro-judge to use shared (#177)
- [ ] streaming input: listen on `GAME READY` to create empty game 
- [ ] streaming input: `bugout-move-accepted-ev`, combine move made with local game state on each request
- [ ] save game state locally
- [ ] streaming output: `bugout-move-made-ev`
