### ISSUE TITLE
🗜️ Support Fedora CoreOS

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#176]
> CoreOS Container Linux will no longer receive updates after May 26, 2020. Begin migrating your workloads to another operating system.

Let's try the official successor, Fedora CoreOS. [Here are the basic getting started resources](https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/), [another intro](https://fedoramagazine.org/introducing-fedora-coreos/), and [some configuration docs](https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/) 

## Tasks

- [x] create minimal startup & provisioning script examples
- [x] generic enough to work in two different environments
- [x] use packer to bake VM images with pre-built branch 
- [x] copied local `.env` files into environment using ignition
- [x] redis config (THP etc) in systemd unit
- [x] caddy config (WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with `ulimit -n 8192`.)
- [x] test everything thoroughly in dev
- [x] [make sure reaper works](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) 
- [x] use for production deploy
- [ ] delete old containerOS docs & cruft

## Memory usage

old t3.medium Container Linux VM

```text
MemTotal:        3979308 kB
MemFree:         1793524 kB
MemAvailable:    1920252 kB
Buffers:           67600 kB
Cached:           449764 kB
SwapCached:            0 kB
Active:          1760416 kB
Inactive:         280408 kB
```

new t3.medium Fedora CoreOS VM

```text
MemTotal:        3962968 kB
MemFree:         2971716 kB
MemAvailable:    3439920 kB
Buffers:            1108 kB
Cached:           626192 kB
SwapCached:            0 kB
Active:           414104 kB
Inactive:         405596 kB
```

**Comment by Terkwood** [comment]
https://docs.fedoraproject.org/en-US/fedora-coreos/running-containers/

**Comment by Terkwood** [comment]
And there's flatcar too https://docs.flatcar-linux.org/os/update-from-container-linux/

**Comment by Terkwood** [comment]
https://terkwood.farm/tech/BUGOUT/fedora_coreos.html

**Comment by Terkwood** [comment]
Let's use packer to provision the things we need on the image

https://www.packer.io/intro/getting-started/provision.html

We can fetch and install Docker-compose 

Also 

```sh
rpm-ostree install htop
```

**Comment by Terkwood** [comment]
Put core user in sudo, Docker groups per fcos guide example
