### ISSUE TITLE
Upgrade rust services to redis-rs latest

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#302]
# Goal

Upgrade all rust services to redis latest version.  

## Tasks

- [x] upgrade gateway
- [x] upgrade BUGOUT redis_streams on branch `fix/redis-streams-r2d2`
- [x] upgrade micro-sync
- [x] upgrade micro-game-lobby
- [x] upgrade micro-judge
- [x] upgrade micro-changelog
- [x] upgrade botlink
