### ISSUE TITLE
🍼 Provide easier / faster modes of playing against bots

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#322]
# Description

Constrain KataGo play time to provide an easier mode of play.

## Implementation plan (first pass, KataGo only)

You only use one instance of tinybrain for this plan. 

- [x] Model difficulty in `botlink/bot-model` (#429)
- [x] tinybrain: just pass the `maxVisits` param as JSON for the request to KataGo. https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md
- [x] botlink: associate client ID with a difficulty setting via repo
- [x] botlink: map `difficulty` to `max_visits` as `const EASY_MAX_VISITS: u16 = 20;` etc, pass to tinybrain; replace use of `const DEFAULT_MAX_VISITS`
- [x] don't mess with gateway beyond making sure that the browser can pass the difficulty param
- [x] browser:  minimal dialog flow, pass difficulty param (#432)
- [x] alter dialog: "KataGo: Full Strength takes significantly longer to compute moves."
- [x] alter difficulty enum & names: "KataGo: Instant Play", "KataGo: Full Strength"

## Evaluation (first pass, KataGo only)

We hope this approach works.  In botlink/src/max_visits.rs we picked arbitrary values for the difficulty levels.  Is the AI considered easy with even tiny values passed?

- [x] do the difficulty settings actually help?!  Yes, but you need to throw stones at a 19x19 in order to see much of a difference.
- [x] Does KataGo caching matter?  No, `maxVisits` is tied to what is cached.  You'll get a diff search using two different `maxVisits`  

## Release plan (first pass, KataGo only)

- [x] test everything in an integrated environment
- [x] update changelog.md, readme.md #444 
- [x] set release versions: botlink, gateway, tinybrain, browser

## Long-term plan: add easier modes of play using an alternative bot

- [ ] investigate GnuGo for easier modes of play #440

**Comment by erlend-sh** [comment]
If this is what it sounds like, it’s exactly what I need. I’ve never played Go before but would love to get started (big bonus to be playing an open source Rust game at the same time!) if the AI can go a bit easy on (I.e have an “easy” difficulty mode) me in the beginning.

**Comment by Terkwood** [comment]
Yeah, I'm in the same boat. I don't think I'll ever be able to beat this AI. So I want to eventually try running the AI using a time-constrained search as mentioned (which will also be a nice option because the player won't need to wait as long for the move to be computed). And if THAT doesn't make it easy enough for newer players, there is another fallback option which would involve a bit more plumbing: I could potentially run a copy of GnuGo https://www.gnu.org/software/gnugo/ in the AWS instance and turn its difficulty way down.

Unlike KataGo AI, which is analogous in design to the AlphaGo/AlphaZero AIs that have received so much popular press coverage, GnuGo is a simpler, rule-based system that doesn't involve neural nets or any of that newfangled magic. For beginners, it's still quite challenging to play

**Comment by Terkwood** [comment]
This config for KataGo looks like what we want. Having a 2 second search time would be an interesting start. Maybe I could win a game 😂

https://github.com/lightvector/KataGo/blob/ac0c91571e1a9e20417897a2a7f3617b4eb3450c/cpp/configs/analysis_example.cfg#L62

**Comment by Terkwood** [comment]
Work is under way in #429

**Comment by Terkwood** [comment]
Constraining the KataGo search space to _two_ moves still yields a relatively difficult opponent.  At least for me (a rank novice).  I'm considering how to advance this issue:  potentially by only offering two modes of play, "hard" and "impossible".  😁

The alternative, which will take more time to implement, but which is probably a better path:  use GnuGo on a low difficulty setting for our "easy mode", and use KataGo AI for "hard" and "impossible" modes.

**Comment by Terkwood** [comment]
One good thing to note about the recently merged work : KataGo is _much faster_ to play with the search space limited

**Comment by Terkwood** [comment]
Just received a report that a friend was able to beat KataGo instant play! We are considering adding an intermediate difficulty. Instant play currently looks at the board TWICE, but full strength looks at it 500 times. Since my skill level is low, it's hard to personally gauge the difference between these two settings - - but my friend might be a good Guinea pig!

**Comment by Terkwood** [comment]
Raised #454

**Comment by Terkwood** [comment]
KataGo is faster now. #440 will track easier modes of play
