### ISSUE TITLE
 🏞 Gateway: coordinate multi-player events using redis streams

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#332]
# Description 

Fully connect gateway to the multi-player micro-stack 

Required by #174.

## Tasks

Emit events in the expected formats for all services.

Read events emitted by the various services, as necessary. 

Watch out for bincode! (see #339) 

https://github.com/Terkwood/BUGOUT/blob/unstable/gateway/src/redis_io/xadd.rs

### Services to add in

- [x] micro-game-lobby
- [x] micro-color-chooser
- [x] micro-sync - compare to micro-judge https://github.com/Terkwood/BUGOUT/blob/2d99cba53ab076c2f73ee2e450104a33c2981d04/micro-judge/src/io/messages.rs#L86

### Model defs to replace

Use new model defs for these services which are already connected to gateway, or  verify that the old ones work 

-  micro-judge 
-  micro-changelog
