### ISSUE TITLE
🐢 Post-prod prioritization

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#395]
These tickets look like they're either very useful, or time-sensitive/bugs

- [x]  Support reconnect in AI play #238 
- [x] style the "invalid private link" message #90
- [x] obey gdpr #416
- [x] social media preview #424 
- [ ]  invalid botlink ack #275 
- [ ] prevent ko popup #124 
- [ ] hangs on tabbing/link sharing? #135 
- [x] play again on game over #271 
- [ ] prevent duplicate OPPONENT PASSED dialogs #481
