### ISSUE TITLE
🤖 Play against KataGo

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/BUGOUT#67]
# Goal

Implement a system which allows playing against a [KataGo](https://github.com/lightvector/KataGo)  instance running on an NVIDIA Jetson Nano. 

## Background 

We picked up an [NVIDIA Jetson Nano](https://developer.nvidia.com/embedded/jetson-nano-developer-kit) board and built KataGo.  [Documentation is available in the repo now](https://github.com/Terkwood/BUGOUT/blob/unstable/tinybrain/README.md)

# Tasks

- [x] build KataGo on the nano
- [x] wrap katago stdin/stdout #190 
- [x] make a basic docker image #189 
- [x]  gateway: backend routing (#205) 
- [x] gateway: send & recv bot attachment and move-making messages
- [x] use websockets correctly #210 
- [x] create botlink service and push game states via websocket (#193, #196, #197) 
- [x] connect tinybrain to Botlink service via websocket and process game states (#194) 
- [x] document reverse-proxy setup
- [x] clean up micro-changelog init (#187) 
- [ ] extend Sabaki initial menu, send attach bot command, process makemoves as normal, `listenForMove` when human plays white
- [x] fix parse error #220
- [x] fix all coords #223 

# Architecture draft

Use [KataGo analysis engine](https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md) to respond to queries.

![76154032-85444100-60a3-11ea-9606-910801c1036d](https://user-images.githubusercontent.com/38859656/76307598-83df6800-629f-11ea-9e42-3adc92538a94.jpeg)

# Errata

- https://github.com/lightvector/KataGo
- https://github.com/leela-zero/leela-zero
- https://blog.janestreet.com/accelerating-self-play-learning-in-go/
- https://github.com/lightvector/KataGo/blob/master/README.md#how-to-use
- https://github.com/leela-zero/leela-zero/issues/2569#issue-547376644

### An existing service for playing against bots

- https://www.zbaduk.com/tools
- [and a related KataGo ticket](https://github.com/lightvector/KataGo/issues/120)

**Comment by Terkwood** [comment]
Some detail on memory usage in KataGo:

https://github.com/lightvector/KataGo/issues/140

**Comment by Terkwood** [comment]
Looks like [KataGo analysis engine ](https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md) is the best path forward when evaluating KataGo

**Comment by Terkwood** [comment]
https://hackaday.com/2019/01/24/running-opencl-on-a-raspberry-pi-gpu/

**Comment by Terkwood** [comment]
Some WIP in https://github.com/Terkwood/BUGOUT/tree/tinker/bots

**Comment by Terkwood** [comment]
https://unix.stackexchange.com/a/33398

**Comment by Terkwood** [comment]
Similar errors here: https://github.com/lightvector/KataGo/issues/54#issuecomment-514569445

Maybe try LeelaZero?

**Comment by Terkwood** [comment]
```text
020-02-29 23:50:14+0000: Performing autotuning
2020-02-29 23:50:14+0000: Found OpenCL Platform 0: OpenCL for the Raspberry Pi VideoCore IV GPU (doe300) (OpenCL 1.2 VC4CL 0.4.145)
2020-02-29 23:50:14+0000: Found 1 device(s) on platform 0 with type CPU or GPU or Accelerator
2020-02-29 23:50:14+0000: Found OpenCL Device 0: VideoCore IV GPU (Broadcom) (score 1000102)
2020-02-29 23:50:14+0000: Using OpenCL Device 0: VideoCore IV GPU (Broadcom) OpenCL 1.2 VC4CL 0.4.145
Setting winograd3x3TileSize = 4
------------------------------------------------------
Tuning xGemmDirect for 1x1 convolutions and matrix mult
Testing 56 different configs
WARNING: Reference implementation failed: CL_BUILD_PROGRAM_FAILURE
Tuning 20/56 ...
```

Lots of failures, whether tuning or attempting to run the `analysis` command

**Comment by Terkwood** [comment]
[pi_run.txt](https://github.com/Terkwood/BUGOUT/files/4271145/pi_run.txt)

**Comment by Terkwood** [comment]
```text
WARNING: Reference implementation failed: CL_BUILD_PROGRAM_FAILURE
ERROR: Could not find any configuration that worked
Done tuning
------------------------------------------------------
2020-02-29 23:31:35+0000: Done tuning, saved results to /home/pi/.katago/opencltuning/tune6_gpuVideoCoreIVGPU_x19_y19_c320_mv8.txt
terminate called after throwing an instance of 'OpenCLHelpers::CompileError'
  what():  CL_COMPILE_PROGRAM_FAILURE
BUILD LOG FOR conv2dNCHWProgram ON DEVICE 0
Precompilation error:
        Pre-compilation: Error in precompilation: Expected no forward declarations!
!3 = <temporary!> !{}
incorrect number of operands in llvm.ident metadata
!0 = !{i32 0, i32 1}
/usr/bin/llvm-link: /tmp/vc4c-w7YRCg: error: input module is broken!

[W] Sat Feb 29 23:31:36 2020: Warnings in precompilation:
[W] Sat Feb 29 23:31:36 2020: <stdin>:127:1: warning: null character ignored
<U+0000>
^
1 warning generated.

[E] Sat Feb 29 23:31:36 2020: Errors in precompilation:
[E] Sat Feb 29 23:31:36 2020: Expected no forward declarations!
!3 = <temporary!> !{}
incorrect number of operands in llvm.ident metadata
!0 = !{i32 0, i32 1}
/usr/bin/llvm-link: /tmp/vc4c-w7YRCg: error: input module is broken!
```

**Comment by Terkwood** [comment]
`vc4c` compilation issues ... `vc4c::CompilationError`

**Comment by Terkwood** [comment]
![Screenshot_20200229-221012](https://user-images.githubusercontent.com/38859656/75618723-50366c80-5b40-11ea-809b-a7abac44dafa.png)

**Comment by Terkwood** [comment]
Similar errors if I try to use `vc4c` to compile `hello_world.cl` example in its own dir. 

```text
[E] Sun Mar  1 13:12:33 2020: Compiler threw exception: Pre-compilation: Error i
n precompilation: Expected no forward declarations!
!3 = <temporary!> !{}
incorrect number of operands in llvm.ident metadata
!0 = !{i32 0, i32 1}
/usr/bin/llvm-link: /tmp/vc4c-wTQaDZ: error: input module is broken!

```

**Comment by Terkwood** [comment]
![IMG_20200307_184227-01](https://user-images.githubusercontent.com/38859656/76154032-85444100-60a3-11ea-9606-910801c1036d.jpeg)

**Comment by Terkwood** [comment]
![signal-2020-03-07-185809](https://user-images.githubusercontent.com/38859656/76154283-cb9b9f00-60a7-11ea-8edd-8f1e00d23307.png)

**Comment by Terkwood** [comment]
[Here's a link which will help when handling stdin/stdout with a katago child process](https://stackoverflow.com/a/31577297)

**Comment by Terkwood** [comment]
Gateway: Take a look at https://redis.io/commands/zrangebyscore for storing client IDs associated with a given backend, scored by time of association

**Comment by Terkwood** [comment]
https://github.com/snapview/tungstenite-rs/issues/113

**Comment by Terkwood** [comment]
Just played the first game against KataGo using our system.  They won ;)

![FIRST_KATAGO](https://user-images.githubusercontent.com/38859656/79702817-83aa9300-8275-11ea-8f8f-04d545fc944b.jpg)
